### ISSUE TITLE
Fulmar immature survival default values are incorrect

### ISSUE THREAD

**Issue by rossmcgr** [naturalengland/Seabird_PVA_Tool#16]
The age specific immature survival survival values for fulmar (up to age 8) are incorrect. For each age class they are provided as 0.26, but this is the compound value for all ages from 1 to 8. The age specific values should be 0.26^(1/8) = 0.845.

**Comment by A-Harwood** [comment]
Many thanks for raising this issue. Natural England and PVA tool partners will investigate this further and provide an update as soon as possible.

**Comment by rossmcgr** [comment]
FYI, this also seems to be an issue with common tern, where the age specific immature survival rates are the compound value across all immature age classes. I would suggest checking all the instances where Horswill & Robinson (2015) have provided a compound survival across all immature age classes against the default values in the app.

**Comment by A-Harwood** [comment]
Please note that we have now identified, and corrected, errors associated with compound immature survival rates for Arctic skua, Atlantic puffin, common tern, fulmar, and razorbill, in the default values used by the tool.
