### ISSUE TITLE
Error when demographic rates not applied separately to subpopulations

### ISSUE THREAD

**Issue by Annet355** [naturalengland/Seabird_PVA_Tool#2]
On the Baseline Demographic Rates tab in the Shiny GUI there seems to be an issue when "Are demographic rates applied separately to each subpopulation?" is toggled to "No" and at the same time "Are baseline demographic rates specified separately for immatures" is toggled to "Yes". The error message returned is "Error in inputs$demobase.survimmat[j, ]: incorrect number of dimensions"

**Comment by katrle** [comment]
This has been corrected in the latest version v4.15
