### ISSUE TITLE
Feature Request - output counterfactual metrics combined for all age classes

### ISSUE THREAD

**Issue by Annet355** [naturalengland/Seabird_PVA_Tool#4]
At the moment the Tables output counterfactual metrics (e.g. Counterfactual of Final Population Size) that are calculated for each age class separately. Typically we have calculated counterfactual metrics across all age classes combined and so it would be useful to add this functionality to the table, chart and download outputs.

**Comment by katrle** [comment]
This has been added in the latest version v4.15
