### ISSUE TITLE
Error when absolute harvest is selected if population falls below harvest level at any point

### ISSUE THREAD

**Issue by Annet355** [naturalengland/Seabird_PVA_Tool#5]
If the "Form of impact" is specified as "Absolute harvest" then the user sets a level of mortality (number of birds) that is applied to each year of the population trajectory irrespective of the population size. The program is generating errors (Error in rmultinom(1, nkilled[k], page[k, ]): negative probability) or sometimes (simpleWarning in rbinom(sim.n, nbyage.prev[, a], p.surv[, a]): NAs produced) or sometimes (simpleWarning in rbinom(sim.n, ntotal.actualbreedpairs * mbs, p.prod): NAs produced) which maybe when some of the projected simulations go below the harvest threshold and so it is not possible to "harvest" the specified number of birds. This causes the program to report an error and no output tables or charts are generated.

**Comment by katrle** [comment]
This has been corrected in the latest version v4.15

**Comment by katrle** [comment]
This has been corrected in the latest version v4.15
